services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    # The following lines are commented out and can be uncommented based on the environment
    # For NVIDIA GPU:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    # For AMD GPU:
    # devices:
    #   - /dev/kfd
    #   - /dev/dri
    # command: ollama serve
    restart: unless-stopped

  moneyme-qa:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL_NAME=mistral
      - HF_HUB_DISABLE_PROGRESS_BARS=1
      - PYTHONPATH=/app
      - VECTOR_STORE_PATH=/app/vector_store
      - UPLOAD_DIRECTORY=/app/uploads
    volumes:
      - ./uploads:/app/uploads
      - ./vector_store:/app/vector_store
      - ~/Documents/pdfs:/external_pdfs
    depends_on:
      - ollama

volumes:
  ollama: